services:
  zeemsv-web-report:
    container_name: zeemsv-web-report
    image: devtrustcv/zeem-report-web:0.0.7
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./.env
        target: /var/www/html/.env
        read_only: true
        bind:
          create_host_path: false
