# Use the official PHP 8.2 FPM image as the base image
FROM php:8.3-fpm
# Set the working directory inside the container
WORKDIR /var/www/html

# Install system dependencies
RUN apt-get update && apt-get install -y \
    git \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip

# Install PHP extensions
RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Copy the application code to the container
COPY . /var/www/html
# Copiar o .env.example para .env
RUN cp .env.example .env

# Install dependencies using Composer
RUN composer install --no-interaction --optimize-autoloader --no-dev

# Generate the application key
RUN php artisan key:generate

# Expose the port that your Laravel application listens on
EXPOSE 8000

# Set the command to run your Laravel application
CMD ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]